version: "3.3"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  spark-master:
    image: cluster-apache-spark:3.2.0
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - shared-workspace:/opt/workspace
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./notebooks:/opt/workspace/notebooks
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: cluster-apache-spark:3.2.0
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - shared-workspace:/opt/workspace
       - ./apps:/opt/workspace/spark-apps
       - ./data:/opt/workspace/spark-data
       - ./notebooks:/opt/workspace/notebooks
  spark-worker-b:
    image: cluster-apache-spark:3.2.0
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - shared-workspace:/opt/workspace
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
        - ./notebooks:/opt/workspace/notebooks
  demo-database:
    image: postgres:11.7-alpine
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=secret!1234

